schema_version: ENC[AES256_GCM,data:eA==,iv:RXm33yYvBNu41V61dZUALbZVuldigvlZNKiEVImDblk=,tag:HbiU4Na9LRuUsSUTS4z3DQ==,type:int]
secret_set_id: ENC[AES256_GCM,data:NSgP4a71,iv:cpIqcKMsPq53mS9OxDnsw7K8tESZYfuFXnNcB83yQGw=,tag:AvFdQ5rVcaFYbHv+D2MpxQ==,type:str]
owner_project_id: ENC[AES256_GCM,data:M6yOb6sT/ko=,iv:rj6sZsVDP+8+XtSmfEM9O7Z5RKEQMhLxGFVapZS4UEw=,tag:eWhaMRIaa4KmBFmDr7yT9g==,type:str]
values:
    platform-sops-decryption-canary: ENC[AES256_GCM,data:7tsrMdIs8dm1g89c5qqRQsSnIJ9E9dZQbFKNHgIhZ79v4uTrn23eCKcfC4AU7cFK7Y6HqE+KMLWjNXJp+Mww1Q==,iv:N+SHUws3r+lveDFYV5LZsiwROtpxwEow/+2XhjzgFcU=,tag:idyz6yGz6+rQmY4ZcAe4vQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SDhNbkpFV0ZsZ2p2aGFJ
            L2N3em1HdWNyWUwydGtVS051Sm5aSkZHLzJjCjFMQ2dKOWk2ekdpc3d6TlBLZEVm
            KzFObWszK1dtWG5Bd1hSN2toUXgvRHcKLS0tIGlpcTdQZ1ZZRWNDTmdzMFM5eGpE
            TndFRFNYaDh2MDlIZ3l6U1RiOGFjZlEK/dMPuQ0OhwjYPcJB5JDQPrUz6aTn+P//
            8Mc/K55cR1lT5v5VW8mHwCHzhKoRM7z0tpusL3LDh2rwX8024A+SUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v48lely3n7c9kh7c6l8nwprcvwyk5g05rrv4c2hmxeyng9qmwvksg30esx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWGVOY2p3YkZpVHBxQWxK
            elhSMXE5NEd4NlVVeDhFSndGRks0TjdKZXpFClN5NmJOUnFaQk9mYXBNVDM5SXZX
            dmJqZW1VSmNGYTlHTXNGK212Ukp2Qm8KLS0tIHN0QUd0QUp1QUM0NVlUTmw1SHNN
            NlhCZk5XVU9PdXZnL2ZEemloRXNyYTAKNrijxnxj/zhP9payzGB0NHWDPmJ24zI3
            QjWCClw+y9U8rqzCMBu1cIcBwgNx3+ZW4bcvAG9A2gN7qqzaSNtDeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jvtwgqeekr4q64hxe4darpqvff9m66k0wx9mm9nxp2n92tn8vscsla9689
    lastmodified: "2026-08-16T20:33:28Z"
    mac: ENC[AES256_GCM,data:0y0JJ/yfTg/IztBeJcu59ivpX4G63Xh7cjLqdp2wbxDxGeeKB96OjDGP1gIIahxVzIAmnw6urpvJgVQeN2J5RmeL1R4ItR4YdXKqRGFFlJT968ewaarG3IjOR/BOZm6Do2X6RGMUsJWIsey7CfoWftMgCJ0YlIm/8OUeSSsJKI4=,iv:6PUP5AUlDR8Bo1VDVZKAQvodo0XjbEl3LZ3l40VSPBU=,tag:XBoc4lKfs6t298gmcaQXCw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
