owner_project_id: ENC[AES256_GCM,data:lkihsNKtb7Y=,iv:cVjXZ2xFNWprE4lR1HIrSRXOyT00+hlcWCP4Vu98SCw=,tag:KkskD3nURg7kNoH46Ja+pw==,type:str]
schema_version: ENC[AES256_GCM,data:YQ==,iv:W6vgzmBOk6yVSemY1qjIewKEQPDXGWn1HdXTnHNy61A=,tag:+GeK6f1s0W/3Yd8oVcNuLQ==,type:int]
secret_set_id: ENC[AES256_GCM,data:ItHBK2l8F1B6UQ==,iv:2vob71IFYU2Aw14i3DwykYNo1FhvAWuK4UVO9LpL5JA=,tag:+G5ZNEgMIWwDvOJ09s4dKQ==,type:str]
values:
    platform-opentofu-state-passphrase: ENC[AES256_GCM,data:KsOfeEvcEeC1tKzgtLqaqqB2uqBiPdn61Nqtf/6HlwX0C1Fq66rD3+EJ9R9PPalpHTh0F2zWhWlgt1Hn4jGhTQ==,iv:uXDQQ/udJLLzboMBU7i8z5GqIorvBix3q4lOtTEqSiY=,tag:csUAfqsJ/JPwS3PFCAZFxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUnl4dEFSeHN1bCs4akdj
            L2xoV2dtRWtpZW9XRVRkTWQvZy91TWJtWm5BCkFzRzBGRmNUZVhWYUFoNkVwOXMx
            MGdqVGpSNlJBdmZKeThUTUZva05GSlUKLS0tIHVtNTVYanBhNnQxayttV1I1N1pR
            WXY5cU16TXY5TFMyU2l4MG93bVdkS3MKGU4jGIx+cwcxUOZ/kIltYwqmfK4wyXWy
            Rj/W282YKGWm85gAZyl5Bj/e/uMIUJ0HonUFG6iVdETWC0vnL8YPTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v48lely3n7c9kh7c6l8nwprcvwyk5g05rrv4c2hmxeyng9qmwvksg30esx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb1h5VmFpalhqaTl0ZVp4
            T3I3am5QMjZZdktXR055RDlmd01HNkhQQXhRCkVRZGFWQzRjSktxbEFpMmVEaVYv
            aUU0SDRxWXNaY1BYOGhoUjFlUzUyeUEKLS0tIGNjYUx1UFNISUYvZnE3WkJkUmdK
            aEtkbDQzNHhVY1RzRDYwSFBCQnJlTDAK+Wj6l0In43Y4ohNaBq/DJbZEUBKWLDNT
            RdWb7heSg5Mr5p2I85GLiebbVa/bIcAfAcAJJggCS/dp817lfi9Qyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jvtwgqeekr4q64hxe4darpqvff9m66k0wx9mm9nxp2n92tn8vscsla9689
    lastmodified: "2026-09-13T15:52:50Z"
    mac: ENC[AES256_GCM,data:eCmPAdR4b53pssqvhFt1S28yD6SnKcv3aY2mSl71wtGJRicyyOe99FRHsIgTKTOmACD7OiQANDUr/RGHG4qRCB4GcKX9Xj7pAit8xjjLbb/9gWgr6ODHdbv4Z8MgTsZ3mJpix0qykk2JkO8i/9hjcciUaQCxhA1L+0RqK7mKbCo=,iv:qs9eD6t+9ZEdQ7mrkzK2jRicdmKwQRJ/KLthKiGVgQw=,tag:UlG5mTJNTxQbRNhstK7uSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
