owner_project_id: ENC[AES256_GCM,data:vK8C/oI5oEM=,iv:ZriLBPi+p0qr0d4IlzKBdoth01rkBI6jIR05Oii3y+o=,tag:X10w2pCDi8G/KvsWoMPadA==,type:str]
schema_version: ENC[AES256_GCM,data:Zg==,iv:+KCkRHiexoL/M0RRY9lUm9zZ3Ie72SKdX3ByiX9FT/U=,tag:STeDll7Mm5K6bjGfbVkY+w==,type:int]
secret_set_id: ENC[AES256_GCM,data:EtgGkvv7GbndwRe8,iv:7x4Nx66FFjZA2Ee1Aki1NWK2eByN3k8jfETIyRf7x80=,tag:tFVw7yvNVxo/HFN5mx2PjQ==,type:str]
values:
    platform-core-backup-access-key: ENC[AES256_GCM,data:BkfGIlFqHfTkyxnjzvpqgVPG0/369ixaJNw+b0h+XUo=,iv:ifpCt4x5FDYOCk5lbF3mEdbmuoL9f+cVwrY4aiqhBm0=,tag:1DDhXdMqQ++vJVDlrFO0oA==,type:str]
    platform-core-backup-secret-access-key: ENC[AES256_GCM,data:u3shvMvponTcbJRD1RErLweCY9GGz9c5W6NUkGy14Jb6wFJLf0qYCvuQlhPgRHWUnJV0grtvw5CXhkqdDWKXYw==,iv:fHJ9ZlBMQNHw3y0wr7NjCA6XtTtqXUM26thVMdsBvbY=,tag:SULb01Q/wncGam7IjK3FvA==,type:str]
    platform-core-restic-password: ENC[AES256_GCM,data:kbxpsZaBHmVpqKNguIMuQNmud9GOZiZcby+tUfXM9pW396fVRgaCkHUjdnQSF0kNwNN/JklYbaODLUN+CzciRA==,iv:N3KnL3D9bp+UPmhDZMjHa2MaSjE3ZDudATfBd9L6xEk=,tag:nzIR+GD3q5ZMFqbkoQBiKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBb1VPcXk2WTcvdnlGNkZB
            WURqb1J1YWFKRE9zZ2dDSmJmMHRKSVB4Y1ZNCkpicFh6NklyVitFTDBnS0txcnF4
            bmFSTmlLR1JXMXVpaFJwRVh4YU9wSm8KLS0tIG1lNE9PY2taSC9aZXpkdjNLc290
            UldSdmI5cWZiQ3NabmFSbHhyT2JJTVEKbwLAsEnVp9FDE2nMj18Ed0kT4AvF31yq
            ZL9oVrG8IpGEIU3fnn70CGwWVizkzfabDC47fia0UP52eAxh+8gN1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v48lely3n7c9kh7c6l8nwprcvwyk5g05rrv4c2hmxeyng9qmwvksg30esx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydGhmak9ibGVVY0JlWXAx
            bXBoc1FzZWlUUEZXVGw2cHJ0QWlLbFdYMVhzCkkrSE5jeVY1SGVDd2NRakFnd0hi
            QndzUnU5Yk4yNGQzRVJKMk1ybmFXL3MKLS0tIDJLSzdsc2dxOVBocTlUV2FVMkxu
            Vk5tMGU5Y2twcC81dUJhTlRacS9jK2cKFg8hSZb9FxHHlXc7Fi7KvUx8W7SxPIIn
            viSMpzx9dEaKaWNZbSS7/iEmzbmRSGKi56HJvEBWDUfmEHFibRtToA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jvtwgqeekr4q64hxe4darpqvff9m66k0wx9mm9nxp2n92tn8vscsla9689
    lastmodified: "2026-09-14T14:57:04Z"
    mac: ENC[AES256_GCM,data:kCt5KGPqFHUP3Rx1ngi4PaWeHMq+P/wnEMt0efOWxMdZ3dH99I0/4jcDXl5XqXuhFSxEvprbOn0E/7Eb2SHCSOu563nwSksEBYEc4BFxz/4VP13BCGuN+hm7pZDSlAyuik/W3tFpfUQnNQLTRWPlEb5ofr2XAnyFz2A/7Bj5lW0=,iv:X1O+CYfJMbkXteTJ/KUnFyovSAFrKHJa/Bvxw+ji1m4=,tag:ibaE8VRJi725HHwDJvSAiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
