owner_project_id: ENC[AES256_GCM,data:+RuCD0pmJtY=,iv:6u1fi7cJ7aeb7D/AivBRxzdnfZ/2dGb2bGxy2cFzNbE=,tag:OnahSxQlxTdW64vN8zL16Q==,type:str]
schema_version: ENC[AES256_GCM,data:yw==,iv:IrJlcWnbY3Z+vbBZnPiHf0HqubEx0lPZSwFEIEcsaCg=,tag:b4pjaIMQxXXW55zHzP+iRQ==,type:int]
secret_set_id: ENC[AES256_GCM,data:Ey0Tq97NMMwJk+R+nrHnkg==,iv:sjpRfBrp5zbuxUX8imcuKYhVBczPhRNPJGAHhH+JwDA=,tag:yioUgECFv1PRaEv7bhKnGg==,type:str]
values:
    platform-publisher-tunnel-token: ENC[AES256_GCM,data:Ja/CZ9HAc2q6REKcHMkxXZ78sUCZIVn9yVTHRuDUIbStv3qp4ylGonlv7xPrXmBXI94qOM0DDmA4XGopDGHYWBWwlvuxm+RSL2cc6g2dd6vHs/3kbhU1SL41Fd6mkmkc2NLxT24aw3scsrbU2Kqzr2cPAO7m/xf+bvkfeAFgX9EN1TMKsuYbUXz/VnzIv06FS7UGuvhAm+SWBaxOhtcOex01W6Ijjk6C8Pd8jJcRR2SJAIzS,iv:Or9DVzLhGBedTkLPXicnocc8yQx2O7A6bPl6VlOHmnQ=,tag:X4+4/AIwb1buzZkrcwZiNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRDJzOTdFT09YOW5MbGow
            eW43T2k0bTZYem4xWjl3TS9lbjNNcmU2RUU0CkhoSkFPNnNDRjR0clJ1dzNGaTNp
            MFhKVnZnRDlYblc2R2g0SjYvL0JyMUEKLS0tIGJWRGdKK2EzK0xVdnhCZXRHK282
            NjVZeEtNT2E5V1JXQjQwODVMbk1kdE0KYHly76cDVHkfdXJnYTrpE1WSu/QnxSo6
            HTQhLVILfd5x9CkWmqQQwtQH8qQ8QRhOwjDqsNX/+zOayxcVuNRjvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v48lely3n7c9kh7c6l8nwprcvwyk5g05rrv4c2hmxeyng9qmwvksg30esx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZXNHYm0wbFBuVlkzdzk1
            NmNIa3loRDdaM2R5b0o0cW9ZTUtrZjJndjBjCjRpT3VPRU83T3lyZ2tuQ2VOZjU2
            M0FUMTNDbmRRSnpZWStjcXdLeHFoc3cKLS0tIHlBbGNUbWZmVnBFUVpKOTJFM01J
            bTdnTW5NU0hEWm9LUHZXYk1Lalp1SlEK0z/vWl3W5HM5ki2wWQS3KAdCPWl2XyJQ
            3dAOc5fBY6LnZiX0ZIWxf4s6olK5kZh59ChuWUvrkXTP6y7BDdOTcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jvtwgqeekr4q64hxe4darpqvff9m66k0wx9mm9nxp2n92tn8vscsla9689
    lastmodified: "2026-09-14T14:58:48Z"
    mac: ENC[AES256_GCM,data:TCoEvDdLCgHvsWr0GZrBPQFyX3+EftZvUvzywzphDU9eRXlls4XiNe4qS2hQIcjZIGEFS7KUcNx5H1/eHN12M7Nc4s90SAL6tb4Gj4RPXoKZvOyIRcW2Xp3WjlAo3l2n7VOoSN/nzbJFAG2+08Q1Y//Kd8DgnC4JzUfMQplVVmk=,iv:ONBX6w7YcmbmExwNFTyEdjc12AhdJH06SoYSPN2nO48=,tag:8r96aM/NCOtQWZGyXwx7nQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
