schema_version: ENC[AES256_GCM,data:Ug==,iv:oYlK77VWZYVX3NHD3Er1X8MIiafGmaGp5UL22HKcMXs=,tag:Nq2ug7kzqBKYWsItosnL2A==,type:int]
secret_set_id: ENC[AES256_GCM,data:Cx0s8oZsUa5F,iv:DKGuIkZU9tgO5kjQ9jMAttcodF3ozATBdgzV7+XloaA=,tag:oq5OqUgqB4AO2Egh+Ryqjw==,type:str]
owner_project_id: ENC[AES256_GCM,data:PxHqD8+zeKk=,iv:IwN4d26lA+KiklbsvrkP5gk7ZOImybKA2GlLnm+ak4E=,tag:dg1goEGB8fZOWhaPL0Hq8A==,type:str]
values:
    platform-publisher-postiz-jwt: ENC[AES256_GCM,data:y/T656aZIobT0BBBzlR5FS87Tj8StRHPmajRPx/veM61UHrI/UQIx0wj95eT8VlFppP5IOjs6osntEwpLUgA/g==,iv:33bD8nPHTFvV7tb3vSfBHYgwbjfA/xO2SjVXOYdHFzo=,tag:0Fncls1bGi1DwNRgBA4Fcw==,type:str]
    platform-publisher-postiz-db-password: ENC[AES256_GCM,data:6GRgBPdBB7yy0XzkOHq6fSMRXjmvjTO4ln92veK50+PxBfR10oVnYwawr86b76PS555R8UcMQpGpMjzqIWUSYA==,iv:L7LlCalwyT1XGqZpMlaVa7ta0rXLS04+wwiNRoP1dPg=,tag:rNXeR11IdK7Zo/TQqahJ7A==,type:str]
    platform-publisher-postiz-redis-password: ENC[AES256_GCM,data:KGDG+lMMcIS1OOTlspNfyoraKcMmjmirc/J0s0kkbIkeRO2hJufqtcBYURzReZjVtxYUHjqwlXFFDxJ8B/dmSg==,iv:CinEwqQAaBjw57DFvDWMh4TFZ9ea8qRvBCxeIlwj1Fc=,tag:TxBQ8+GOUhhIVb5VDF2Xtg==,type:str]
    platform-publisher-temporal-db-password: ENC[AES256_GCM,data:1V07qq/n5G1tpL+ueNz1r5tg2oiL8vsdPAC08a/t1IpkqwuJtA1u+FXoaD+nVCoO077frSicloYZvhcd87EwKQ==,iv:RjaEoFKRpIV0xwQh7HHuN5SUNsJJKoRJ2DcYmoul1fY=,tag:pfchQ+2OEnDgazlhG6jM3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd2lqbWcrRlJzVUVHMEZO
            Q3BGeUFUOHQ3V2IvQUtKNzV2eUZya0hmZDI4CmNZbnZJWFFtYTg0MzFVZGZQMlQz
            K3B5RXpJRGVCOWJiZDBsUWZ6eDBseVEKLS0tIFJVWmdmTCt3cDlsOFNpUFdYRHVv
            dGtKckR5c2s0S1ZVeXBEaDNFZVkrSnMKoLt2yWO7iBf5TOH7Yud0A1zSvwy9BJ4r
            vd2OBi6M6SGjpUOc3pGqziFRaAbOcHC4z0dEXMF0K7tp4uCt+ou1jQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v48lely3n7c9kh7c6l8nwprcvwyk5g05rrv4c2hmxeyng9qmwvksg30esx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VWU5Mmd6V2x3YmlHVVo3
            M056REZXb0ZQL0E4Ulg5SFk4ejdESWp4MmxRCk1JYStmcUZ4cDczcnVydmhoeXZU
            a3ZkNlhXbWJtaEQvVkN2VHR1eHVwR3MKLS0tIHcyQnlxeWFKV1h2b3pSR1B2Ky9Q
            Y09NUzVWU0FENU94SmRMQ2ZpNmRsL00K1F+3LpXpAgUt1zb+xBgLfXMoQaTCh42m
            YRkENgLOc+n+F/P/W7hoduqZvUuQNZA4Xz/rUOlXPo+Vfua+XTF5Wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jvtwgqeekr4q64hxe4darpqvff9m66k0wx9mm9nxp2n92tn8vscsla9689
    lastmodified: "2026-09-15T05:06:23Z"
    mac: ENC[AES256_GCM,data:nMHuZfqsEwB9o9+LQ3DcpPS33FxT3H+VuBBT54TRgsRQKf8HbiP5DLpZR3WzKopOuZRlSK8Gmwtys4ha8iZNJ7ZEBO/SsdsHfz4XH97Bo9KVT5VrGSSEWwPjOqdZg24STu3qrTI9VZeKFl+VsY50B9oq0maVkaZWtue4/zaZO0o=,iv:AgJtIrPLrBie1sqzQ2bhxCheh6WW7irQ3sWonVtV1Y8=,tag:Zuv6uY7pCTwqzvtS87/imA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
