owner_project_id: ENC[AES256_GCM,data:u+nB2qVFOys=,iv:vxJhTa0RtUqLxTgvcaDlrpGm1rsD16KBYdlwCoD6+Zc=,tag:CGdmI9Y6ge2k0rSTlCQSDg==,type:str]
schema_version: ENC[AES256_GCM,data:UQ==,iv:8bJEzs2rV9Y80JqvUmXmL894Stwfx9njl58nvszU/T8=,tag:HQQuSWjApzj9Ewy+VGLiRw==,type:int]
secret_set_id: ENC[AES256_GCM,data:1S99aJdkM72feCE+nI8bGQ==,iv:Xpc19GLqr1o7G1loKAeD9QCTNHPDTsXZYQTV8QM0fY8=,tag:uR9Yiy+HT3EF2OHa7HXM+A==,type:str]
values:
    platform-n8n-publisher-access-client-id: ENC[AES256_GCM,data:/SE7KM4UBmY3gQAhApUAexc68SKcGlgNwN2OKhqx/QkRTNTAuvNV,iv:u8JHYmWmP/aOf5i3LCMbxvsuLGTx9M/hQwd++6yJBCc=,tag:TLLPdXvF9aPhl2awDHO2lw==,type:str]
    platform-n8n-publisher-access-client-secret: ENC[AES256_GCM,data:dxjEwsC90GJGcBWjGiXj78SeIngcmv6qLj5qdWkuRqOo9wZvTKe77AGZ3AcyZeZPYtAFsODp,iv:kJ6OO/owBvhREzb2YwYZjjRb96AJWoHQ2sgRVgT7Lrc=,tag:fjnEbFg0JaZIMw17SB9+iQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySnZFK0R1UmdxalV5aGhj
            TzJsbnFFTysycVl5ZnBHbDdMK2ZlbmhITGhFCllLTUxMcE1RTngvZkQ1aDJKZGhJ
            TzQxNWVBazJLck5XUTY2RTRCR3kyN0kKLS0tIEZ4TGJBekYvL0oyTUcxK0UxaWpE
            b2hud0VORnBjNXRXU01COTQ1ekk0K1EKHbyixCbt4LOQ+cQZnX3rH/kutdXhuiig
            Vu3FhBQEJfBxXz3GsOe+o5W2+t3zbMuGJXinqtvcbJCNAoIVoRtcwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v48lely3n7c9kh7c6l8nwprcvwyk5g05rrv4c2hmxeyng9qmwvksg30esx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQmd6aXpqVDR1cWlFMURo
            RWpJOGNHWTM3bFFKbitsTnZHRHQ2M0JSUHdFCjcxY3JQY0RqT2N2eGQvYTZxdFdz
            aFc1Qi9lZTVYUHVYY1FOQU5lS3hQUUUKLS0tIGVBcFova0djTVMwQXdicW44a0Iv
            aWR0cGIweHpDbUlCb21YL2N1VnRSSnMKT49zpB4cMkl0eedLHkO3ztOvG2Tre0GG
            i9FtuNJOoKS5w5h1mjLEfdukz698xC7grR/eN+UzbJvvxSVihbHVwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jvtwgqeekr4q64hxe4darpqvff9m66k0wx9mm9nxp2n92tn8vscsla9689
    lastmodified: "2026-09-14T10:49:45Z"
    mac: ENC[AES256_GCM,data:Fv5bNTXseA1LxKI9ldvp023GJ1UQUt98UAW8oJvTMbZh4tShGNYX5ySqxN3zcO22M9+u7Q+CAi0AsFDZhBMMHu1FmlDTaDLO+hJ9w133frYHkaruujX/tk0AGL0uOkR82hnP7QfhTFI3tupDtP1vTRZabXzzPcCsI2qbYQyZnLY=,iv:nrOVqnogBKvSW0QpvcLN9DTvkQ/p/bgClZ4iEFbIsIc=,tag:menzujXM5O13r1CAwVF1cA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
