owner_project_id: ENC[AES256_GCM,data:QeyMHHJCE/M=,iv:MlA6NSwNHUr58bPQGXXz0hMni/8R3pNN6IJIGedy6Do=,tag:41mWfKnfx5jWvFN6X2fn+Q==,type:str]
schema_version: ENC[AES256_GCM,data:+A==,iv:ZQVNBgL0gYoAFTc0udo4WkP8p0ZsV122yl4L6t21bF8=,tag:XmRTp2QIlG3QwaqGwv4Rag==,type:int]
secret_set_id: ENC[AES256_GCM,data:U6yVjBsi81CpoujdxJI3sqk=,iv:eZ44zILZUKeUBrcvrXefh1YPPzwqed+ss5YMfu213uY=,tag:VFt6/VCS6FU3p8tkMdHAZA==,type:str]
values:
    platform-publisher-backup-access-key: ENC[AES256_GCM,data:4VxyLuMg8XvEvNj4pt8s9iDVTpO5WHKJQr6jixFVSi0=,iv:AQI0LO7Swv0LFg0MzR/gq3M7zj8swIwRLO5D2WoLQgQ=,tag:OfOrdX1uyCBKlIC5LjriPg==,type:str]
    platform-publisher-backup-secret-access-key: ENC[AES256_GCM,data:4hlrD/sNEPTg0vn3n0zalKKlIHw+XY2xSVqF+qR8d5f8wD+Em7VjvtFhzOxQW2+Z16X5nSmmtO6f8NFyDicviQ==,iv:iBP0hi2zlXjoMXZr5DeXUgcgJwdwOvBRmKE2FULRe/8=,tag:EKhR7OfcrVcZhGWcqyu8Kg==,type:str]
    platform-publisher-restic-password: ENC[AES256_GCM,data:9Ftvic69kAtIYNlv0LAJzjdL20pZh48MO/KvzpzJtW+MS/2/vzs6tnb8x8uQNCWHsBUiTZ3kVvJXl+vwo44SwA==,iv:JUmZB/4hBmRqR6Pp6jhV+Nqy+4mENsdYGOq3fChbADc=,tag:ceqaM9y1rj948EZBWKTx7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNTN1OHE4Snp1bDhBQ1lH
            S2o1c3BnUWhvVFZsMUdGTHY5ZnpORkJ5UkFBCmEvdlFLWmlVMFdpanlrQkp5Vk10
            NXRMK3cwTFhReG84dTNjd3JoMDhKZWcKLS0tICtxNjBjOHdjSk5wTWZ3QUFFSzg1
            U1RMVDRrWWdGZDBCU1JIb1BRcUNBNGcKlxbe1qmqLjjX4YDEHxzjJCElX0BNmToM
            slNbBY4AmPEJh6wYk+ybN2TZJuVUGI4KflTMqLNd17m3BSO49murwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v48lely3n7c9kh7c6l8nwprcvwyk5g05rrv4c2hmxeyng9qmwvksg30esx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZnozbEp4NUpBWHVreWti
            WElJd1Z3c3dIam01SXdGQ0dpZVpMczJ1SGpnCnA3UXNCbUFFTDhHanV5L0VtWXhQ
            MlBidE96eHpET2F3d1VwVnVpUHpTZE0KLS0tIHpaMml4NE80eVBNNGZBOTF6OERz
            NVRUbzN6N1dIVFdoQ3NNTFBNYXRZb1UKrVp400g03Ov08m2IjLYAH3hL4A12/iU8
            oHWrtN9H/SogABYshety+M1wvCU4eyT9M/knpZ8iQbEPcWVUvTHBdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jvtwgqeekr4q64hxe4darpqvff9m66k0wx9mm9nxp2n92tn8vscsla9689
    lastmodified: "2026-09-14T14:57:06Z"
    mac: ENC[AES256_GCM,data:jS8VN7esrpUUq+yA/K3SFrdpWKB6vFdqIJ0fxDH0D0eYjHGsxSJKnOJNNuemLGyduHxqrG0xtoNKkT5HhuVCCykvc08IQfNz6zYu2jKC48tl+x+xhP6e1L0yTuh14LBQ0kkl8SJjolXTlWRVplH0k1O3kaIf0bB1zY2C057KsV4=,iv:BDoKqa/F6Rb520jnewyV6GXs5anLvQvQfpkY0igEkuw=,tag:raQxBibuPL+EZZvpPSHU5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
