owner_project_id: ENC[AES256_GCM,data:XXh/9IGA2q4=,iv:H0km+9zltxyirE5nzwuMVsuGzQq3Cyh1k43mdq8FXu4=,tag:ze1REUXj0svmejGNUV49FQ==,type:str]
schema_version: ENC[AES256_GCM,data:Fg==,iv:/j2E7ErcqFFKiozsaMHIIFmUhTgjSgPXrAsLF2jDDf4=,tag:UNoAmAd72vY+d1nlNn3CRg==,type:int]
secret_set_id: ENC[AES256_GCM,data:iMW4cDCy6QEHf/jfxLau,iv:npnq6tg82NjsbkG5ZR+94ivgRgKwzc4WoRGkT4hJTJw=,tag:+jhMHixE+WLWb3rck1BjMA==,type:str]
values:
    platform-publisher-media-access-key: ENC[AES256_GCM,data:NL62FZfk3eo4JVheHrmyklSaQZg2Rlc5/TWA/kVV2D0=,iv:OM+N0UrmWkDKozuqT4nM47zO/TQC4RQeXV+GOQI1rkM=,tag:W6HCF3Vc4+y4ANc6wDGugA==,type:str]
    platform-publisher-media-secret-access-key: ENC[AES256_GCM,data:ZITDh3MtcuRo2TXJjPN9RDQ7TfWS8FaagTjjU4GGXnocZ6S2KHh10lDN1SlDIqWavqcTUrAfbz4ed5+/Tk+Lwg==,iv:8ZWChfVUSooGvrH4AwODryW5BT1hXUYdhEekpXGejYM=,tag:Om72ij+qao7U2xNjFARThQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScDJjZ2ZuMUE1cFRPdTgv
            Ui8wUDBXVWp0MVB0NlF6RkJHelB0dkZHN1JvCkZCQXpsVHArckFjd0xJc1F6TG4x
            QWhoRFdSMHVmTWFXUWE5cXNCSzRlVDQKLS0tIFdpcUlxcSthWEdGZnJ1QUJWUU9o
            UE1CR2VXbE5YaE9rcEMyOXZ1aWFXSkkKXxkcp6m4CvlhOMAlzucEOXusUmr/hMEC
            2esEXbfUl87HXZCxhJiMh3QuxZ7hec5Co8W9S1K+j3kms1Xolx91TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v48lely3n7c9kh7c6l8nwprcvwyk5g05rrv4c2hmxeyng9qmwvksg30esx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXelZrWmYzZnMvdXFaUUF3
            cFlPeXcxQ3YwTVg0c0FLeHlyTHF1OTdic0E0CkduQTBMbnhFZTg5YmYxckp2Vzlt
            Tm9xdGthcy84eW5JQncxWk1pNUNJUjgKLS0tIFR5VzV3N0FleDVPVWRDejkxWTFx
            MEMzek93SXB4ZUxOdTFCSVg4OURLRnMK14UVxYdJ5agfvGdyfHm5ZW9THp+IWINI
            LfBHJqW03+b4CiDjiAD1cCLfvgQlj21lU6bT92RBG+3KwYKFnI/Myw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jvtwgqeekr4q64hxe4darpqvff9m66k0wx9mm9nxp2n92tn8vscsla9689
    lastmodified: "2026-09-14T14:57:08Z"
    mac: ENC[AES256_GCM,data:LNl3kwn4vcaWcoh7UHUJLSwxHYXY4aWzjXWqn2d39hGaaVI+qnxhsfSrS/Nfav90kdyvaNIGON3idx6HRD2ZQgx/kWCIW9o52KePBocvmEJSSs/19YDLeguozxW1ROQ9riCu3BOR2LJmWPiz3RgyMkVi0psnO7+Co1fxQn84Lzw=,iv:BgT+uVsUypgyqvkr0P9INj56aNe3sN2r0unFSB33hts=,tag:XC9NvoqS6CIEl9A2BcSo8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
