owner_project_id: ENC[AES256_GCM,data:Es9PnvI60H0=,iv:tyMrYVax4wAdGLNOyWbsB7EkGSetVj/g31oClj7pmro=,tag:5PudT46sJLBpBpysNhTyIw==,type:str]
schema_version: ENC[AES256_GCM,data:WA==,iv:C13DKdmIE5BBAeC3WCLAnqczTKNF4z2hvWGDKbzTl9I=,tag:iTxx8D1ZjdAoFDWyTOttGg==,type:int]
secret_set_id: ENC[AES256_GCM,data:+q5J1w/d7NlOmRS8RA==,iv:4SKK2+ERA9bqFBizKTKtsaHykNYMezpCJb3q9SlWEcM=,tag:UdnrNHwQCZaOLjgQb6ooyQ==,type:str]
values:
    platform-source-escrow-access-key: ENC[AES256_GCM,data:Z/0d9XKT8Il/tCDP2kv6Ff/V+BSOicBbrjqGLB3hTzw=,iv:rd1N1436tVJ3SqKCqU7gMR3CJoxcXDtMoZEpl+hOq8I=,tag:nRpwb+IoOHXT03oEy8xtUg==,type:str]
    platform-source-escrow-restic-password: ENC[AES256_GCM,data:XZhgonjR5lKNl09PTxZSNn4CC/ZaFyTXueanE1Vf8VMzNbzk1ilO2BFE4S8PYADGBlyiVW5LbgzuLN0bYmSUvg==,iv:3YhVBE/oS4bDSjxWyyKaI/9H4IpK6/va2qE97+GjbRY=,tag:5pzTjcJEl1bYcvBQil1QQA==,type:str]
    platform-source-escrow-secret-access-key: ENC[AES256_GCM,data:3Wz5J5QW3XgFrs6QjbY4OWc11aQ7BT4T3q6XX7BDtR73ZxeV2ApvLpItVSE3u3V8ykvXKcMuYpfBVWJPumSXsw==,iv:h5cdx9g6vmiv5hSCjqzGG3PJ6CeQxIu+4eUSkJ6KXe4=,tag:OTMPh6v8tgqwGwGD4TX2DQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITFBvNU4yWGFDZHhHSzVa
            VVNnWFZUSmo4c3c1Nlh4dTE4Q2liR2Nza0hBCkd0Ry9mL3dmd3JaOS9PeVJjdnht
            elRCVGZKRERvSm9aSjlCSkcvL2xRcVEKLS0tIHhMaXFtYVI1aVRpdkVKTlNHcXM4
            Vk5OS0pmWUdqd0dPV0lSSjZmK2xCRTQKQN6b71pwkZMQbo/CRQRlQdxBURnGBBq0
            5UUdpdt5uD4SzbFoL6X11pY+xpUmFUCOaGvNKlHWvX8NRgb8abp9Rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v48lely3n7c9kh7c6l8nwprcvwyk5g05rrv4c2hmxeyng9qmwvksg30esx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZXNTVVhqd1lBYzQ1QWFt
            RzVCVGZoZWFZN053K213Z0lkV2QyT1YyUEJjCjI1UVU5ZUU5bVlSLzV2eWc2SGNx
            ZDFKa1JYY25lSEVjS2NMTWR1MTdKZjgKLS0tIGJLOGJtRTZvOWdnUHlXLzBOMFdk
            bDZYTk00SUk5M1EvSG9zaGhjUzFOeVUKPOgVdg129aSW4hu+ZQOZ8LcQGgvyKSaL
            DBhpO8WeG8gDKn+5FCKbSV93aa0cN8XUhEygqySmv5tpyI0OHxFkmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jvtwgqeekr4q64hxe4darpqvff9m66k0wx9mm9nxp2n92tn8vscsla9689
    lastmodified: "2026-09-14T14:57:10Z"
    mac: ENC[AES256_GCM,data:7DwepWmyBzeFc2T7GYFdb4isEsQGq4wgDvGkcNFeE1rrXU2CO3HeraViCKBFS0XH4laO1rF8OM8A7ZO5yx8A7D8jCZt8KsovEOuYJoboxxv4Hu8iOo7ehP5RvHkisM5VfCuJl95tFA5uJ8WcM7pc0FbKABJ/cr1XrdpGXMmyv7Y=,iv:YPy7iqgLrVwcNO8uls1qdInuV0OOmULcWicFvQh7Uz4=,tag:Z1tc0dUlfY/2LX8OXaiNfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
