---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart Dholbeat Docker firewall
  ansible.builtin.systemd_service:
    name: dholbeat-docker-firewall.service
    enabled: true
    state: restarted
