---
extends: default

rules:
  comments:
    min-spaces-from-content: 1
  document-start: disable
  line-length:
    max: 240
    level: error
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
